# Generated by Django 6.0.1 on 2026-02-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên thuốc')),
                ('price', models.IntegerField(verbose_name='Đơn giá (VNĐ)')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Nhà thuốc')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(default='090xxxxxxx', max_length=20, verbose_name='Số điện thoại')),
                ('opening_hours', models.CharField(default='8:00 - 22:00', max_length=100, verbose_name='Giờ mở cửa')),
                ('desc', models.TextField(blank=True, verbose_name='Thuốc & Dịch vụ')),
                ('has_stock', models.BooleanField(default=True, verbose_name='Còn thuốc')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pharmacies/', verbose_name='Hình ảnh')),
                ('lat', models.FloatField(verbose_name='Vĩ độ')),
                ('lng', models.FloatField(verbose_name='Kinh độ')),
            ],
            options={
                'verbose_name': 'Nhà thuốc',
                'verbose_name_plural': 'Danh sách Nhà thuốc',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='myapp.pharmacy', verbose_name='Nhà thuốc'),
        ),
    ]
