# Generated by Django 6.0.1 on 2026-03-31 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ten thuoc')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Danh muc')),
                ('unit', models.CharField(default='Hop', max_length=50, verbose_name='Don vi tinh')),
                ('manufacturer', models.CharField(blank=True, max_length=150, verbose_name='Nha san xuat')),
                ('origin', models.CharField(blank=True, max_length=150, verbose_name='Xuat xu')),
                ('price', models.IntegerField(verbose_name='Don gia (VND)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='So luong ton kho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/', verbose_name='Anh thuoc')),
                ('gallery_urls', models.TextField(blank=True, verbose_name='Bo suu tap anh')),
                ('description', models.TextField(blank=True, verbose_name='Mo ta ngan')),
                ('usage', models.TextField(blank=True, verbose_name='Cong dung')),
                ('ingredients', models.TextField(blank=True, verbose_name='Thanh phan')),
                ('dosage', models.TextField(blank=True, verbose_name='Cach dung')),
                ('prescription_required', models.BooleanField(default=False, verbose_name='Can ke don')),
            ],
            options={
                'verbose_name': 'San pham thuoc',
                'verbose_name_plural': 'Kho Thuoc va San pham',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ten nha thuoc')),
                ('address', models.CharField(max_length=255, verbose_name='Dia chi')),
                ('phone', models.CharField(default='090xxxxxxx', max_length=20, verbose_name='So dien thoai')),
                ('opening_hours', models.CharField(default='8:00 - 22:00', max_length=100, verbose_name='Gio mo cua')),
                ('desc', models.TextField(blank=True, verbose_name='Mo ta dich vu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pharmacies/', verbose_name='Hinh anh')),
                ('gallery_urls', models.TextField(blank=True, verbose_name='Bo suu tap anh')),
                ('lat', models.FloatField(verbose_name='Vi do')),
                ('lng', models.FloatField(verbose_name='Kinh do')),
            ],
            options={
                'verbose_name': 'Chi nhanh',
                'verbose_name_plural': 'Quan ly Chi nhanh',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gio hang tam',
                'verbose_name_plural': 'Gio hang dang hoat dong',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.cart')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
            ],
            options={
                'verbose_name': 'San pham trong gio',
                'verbose_name_plural': 'San pham trong gio',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nguoi nhan')),
                ('phone', models.CharField(max_length=20, verbose_name='SDT lien he')),
                ('address_text', models.CharField(max_length=255, verbose_name='Dia chi giao')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chu cua khach')),
                ('delivery_lat', models.FloatField(blank=True, null=True, verbose_name='Vi do')),
                ('delivery_lng', models.FloatField(blank=True, null=True, verbose_name='Kinh do')),
                ('distance_km', models.FloatField(default=0, verbose_name='Khoang cach (km)')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='Phi ship')),
                ('total_product_price', models.IntegerField(default=0, verbose_name='Tien hang')),
                ('final_total_price', models.IntegerField(default=0, verbose_name='Tong thanh toan')),
                ('status', models.CharField(choices=[('pending', 'Cho xu ly'), ('shipping', 'Dang giao hang'), ('completed', 'Hoan thanh'), ('cancelled', 'Da huy')], default='pending', max_length=20, verbose_name='Trang thai don')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian dat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tai khoan khach')),
                ('pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.pharmacy', verbose_name='Chi nhanh xu ly')),
            ],
            options={
                'verbose_name': 'Don hang',
                'verbose_name_plural': 'Xu ly Don hang',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.order')),
            ],
            options={
                'verbose_name': 'Chi tiet san pham',
                'verbose_name_plural': 'Chi tiet san pham',
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='myapp.pharmacy', verbose_name='Thuoc chi nhanh'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Ho ten hien thi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='So dien thoai')),
                ('address_text', models.CharField(blank=True, max_length=255, verbose_name='Dia chi mac dinh')),
                ('address_lat', models.FloatField(blank=True, null=True, verbose_name='Vi do mac dinh')),
                ('address_lng', models.FloatField(blank=True, null=True, verbose_name='Kinh do mac dinh')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ho so tai khoan',
                'verbose_name_plural': 'Ho so tai khoan',
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key',), name='unique_cart_session_key'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'medicine'), name='unique_cart_medicine'),
        ),
    ]
