# Generated by Django 6.0.1 on 2026-02-05 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Thuốc', 'verbose_name_plural': 'Danh sách Thuốc'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn đặt hàng', 'verbose_name_plural': 'Quản lý Đơn hàng'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/', verbose_name='Ảnh thuốc'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_text',
            field=models.CharField(default='EXIT', max_length=255, verbose_name='Địa chỉ cụ thể'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(null=True, verbose_name='Vĩ độ giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(null=True, verbose_name='Kinh độ giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(default=0, verbose_name='Khoảng cách (km)'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_total_price',
            field=models.IntegerField(default=0, verbose_name='Tổng thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Họ tên người nhận'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.pharmacy', verbose_name='Chi nhánh xử lý'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Số điện thoại'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.IntegerField(default=0, verbose_name='Phí ship'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('shipping', 'Đang giao'), ('completed', 'Đã giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_product_price',
            field=models.IntegerField(default=0, verbose_name='Tổng tiền hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.cart')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
