# Generated by Django 6.0.1 on 2026-02-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_order_branch_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.CharField(default='', max_length=255, verbose_name='Địa chỉ cụ thể'),
        ),
    ]
