# Generated by Django 6.0.1 on 2026-02-06 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_note_alter_order_address_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pharmacy', verbose_name='Làm việc tại')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản nhân viên')),
            ],
            options={
                'verbose_name': 'Hồ sơ Nhân viên',
                'verbose_name_plural': 'Phân công Nhân viên',
            },
        ),
    ]
