# Generated by Django 6.0.1 on 2026-02-06 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_staffprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Giỏ hàng tạm', 'verbose_name_plural': 'Giỏ hàng đang hoạt động'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Sản phẩm thuốc', 'verbose_name_plural': '2. Kho Thuốc & Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': '3. Xử lý Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Chi tiết sản phẩm', 'verbose_name_plural': 'Chi tiết sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name': 'Chi nhánh', 'verbose_name_plural': '1. Quản lý Chi nhánh'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Nhân viên', 'verbose_name_plural': '4. Phân công Nhân viên'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='myapp.pharmacy', verbose_name='Thuộc chi nhánh'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.CharField(default='', max_length=255, verbose_name='Địa chỉ giao'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đặt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(null=True, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Người nhận'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú của khách'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='SĐT liên hệ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý (Mới)'), ('shipping', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái đơn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_product_price',
            field=models.IntegerField(default=0, verbose_name='Tiền hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản khách'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pharmacy', verbose_name='Làm việc tại chi nhánh'),
        ),
    ]
