# Generated by Django 6.0.1 on 2026-03-06 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_cart_options_alter_medicine_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Sản phẩm trong giỏ', 'verbose_name_plural': 'Sản phẩm trong giỏ'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'Sản phẩm thuốc', 'verbose_name_plural': 'Kho Thuốc & Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Xử lý Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ['name'], 'verbose_name': 'Chi nhánh', 'verbose_name_plural': 'Quản lý Chi nhánh'},
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='has_stock',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.CharField(max_length=255, verbose_name='Địa chỉ giao'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('shipping', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái đơn'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Mô tả dịch vụ'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên nhà thuốc'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key',), name='unique_cart_session_key'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'medicine'), name='unique_cart_medicine'),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
