# Generated by Django 6.0.1 on 2026-04-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('momo', 'Vi MoMo'), ('bank', 'Chuyển khoản ngân hàng')], default='cod', max_length=20, verbose_name='Phuong thuc thanh toan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('cod_waiting', 'Thu tiền khi giao hàng'), ('awaiting_transfer', 'Chờ xác nhận thanh toán'), ('paid', 'Đã thanh toán')], default='cod_waiting', max_length=30, verbose_name='Trang thai thanh toan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('shipping', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trang thai don'),
        ),
        migrations.AlterField(
            model_name='returnrefundrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Đang xử lý'), ('approved_refund', 'Chấp nhận hoàn tiền'), ('rejected_refund', 'Từ chối hoàn tiền')], default='processing', max_length=20, verbose_name='Trang thai xu ly'),
        ),
    ]
