# Generated by Django 6.0.1 on 2026-04-14 01:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_order_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='product_type',
            field=models.CharField(choices=[('medicine', 'Thuốc'), ('supplement', 'Thực phẩm chức năng')], default='medicine', max_length=20, verbose_name='Loai san pham'),
        ),
        migrations.AddField(
            model_name='purchaseimportbatch',
            name='imported_by_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email nguoi phu trach'),
        ),
        migrations.AddField(
            model_name='purchaseimportbatch',
            name='imported_by_role',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Chuc vu nguoi phu trach'),
        ),
        migrations.AddField(
            model_name='purchaseimportbatch',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='imports/receipts/', verbose_name='Phieu nhap PDF'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Phan quyen quan tri chi tiet'),
        ),
        migrations.AlterField(
            model_name='medicinepromotion',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Phần trăm giảm'),
        ),
        migrations.CreateModel(
            name='StockExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_code', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Ma phieu xuat')),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='exports/receipts/', verbose_name='Phieu xuat PDF')),
                ('exported_by_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Ho ten nguoi lap phieu')),
                ('exported_by_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email nguoi lap phieu')),
                ('exported_by_role', models.CharField(blank=True, default='', max_length=120, verbose_name='Chuc vu nguoi lap phieu')),
                ('destination_name', models.CharField(blank=True, default='', max_length=180, verbose_name='Noi nhan / muc dich xuat')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chu')),
                ('total_lines', models.PositiveIntegerField(default=0, verbose_name='So dong xuat')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Tong so luong xuat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian xuat')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_export_batches', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi lap phieu xuat')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_export_batches', to='myapp.pharmacy', verbose_name='Chi nhanh xuat kho')),
            ],
            options={
                'verbose_name': 'Phieu xuat kho',
                'verbose_name_plural': 'Phieu xuat kho',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='Ten san pham')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=150, verbose_name='Nha san xuat')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Don vi tinh')),
                ('previous_quantity', models.PositiveIntegerField(default=0, verbose_name='Ton truoc khi xuat')),
                ('exported_quantity', models.PositiveIntegerField(default=0, verbose_name='So luong xuat')),
                ('remaining_quantity', models.PositiveIntegerField(default=0, verbose_name='Ton sau khi xuat')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chu dong')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.stockexportbatch')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_export_items', to='myapp.medicine')),
            ],
            options={
                'verbose_name': 'Chi tiet xuat kho',
                'verbose_name_plural': 'Chi tiet xuat kho',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockExportLotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng phân bổ')),
                ('lot_expiry_date', models.DateField(blank=True, null=True, verbose_name='HSD snapshot')),
                ('lot_import_price', models.PositiveIntegerField(default=0, verbose_name='Giá nhập snapshot')),
                ('lot_source_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Nhãn lô snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='myapp.stockexportitem', verbose_name='Dòng phiếu xuất')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_export_allocations', to='myapp.medicinelot', verbose_name='Lô thuốc')),
            ],
            options={
                'verbose_name': 'Phân bổ lô cho phiếu xuất',
                'verbose_name_plural': 'Phân bổ lô cho phiếu xuất',
                'ordering': ['id'],
            },
        ),
    ]
