# Generated by Django 6.0.1 on 2026-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_medicine_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexportbatch',
            name='export_scope',
            field=models.CharField(choices=[('standard', 'Xuất nội bộ / chuyển kho'), ('reconcile', 'Đối soát tồn vật lý'), ('expired', 'Xử lý hàng hết hạn')], default='standard', max_length=20, verbose_name='Loai phieu xuat'),
        ),
    ]
