# Generated by Django 6.0.1 on 2026-04-14 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_stockexportbatch_export_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('password_reset', 'Đặt lại mật khẩu'), ('username_recovery', 'Khôi phục tên đăng nhập')], db_index=True, max_length=40, verbose_name='Mục đích xác thực')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email nhận mã')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Mã công khai của phiên OTP')),
                ('otp_hash', models.CharField(max_length=255, verbose_name='Mã OTP đã băm')),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150, verbose_name='Tên đăng nhập snapshot')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Thời điểm hết hạn')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần nhập sai')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đã dùng xong')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_otp_challenges', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Phiên OTP khôi phục tài khoản',
                'verbose_name_plural': 'Phiên OTP khôi phục tài khoản',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['purpose', 'email'], name='idx_otp_purpose_email'), models.Index(fields=['user', 'purpose'], name='idx_otp_user_purpose')],
            },
        ),
    ]
