# Generated by Django 6.0.1 on 2026-04-20 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_aboutpagecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('hero_autoplay_interval', models.PositiveIntegerField(default=4000, verbose_name='Thoi gian chuyen slide (ms)')),
                ('category_section_kicker', models.CharField(default='Danh muc noi bat', max_length=120, verbose_name='Nhan khoi danh muc')),
                ('category_section_title', models.CharField(default='Tim thuoc theo nhom san pham', max_length=180, verbose_name='Tieu de khoi danh muc')),
                ('category_section_link_label', models.CharField(default='Xem tat ca', max_length=80, verbose_name='Nhan nut xem them danh muc')),
                ('category_section_link_url', models.CharField(blank=True, default='/products/', max_length=255, verbose_name='Lien ket nut danh muc')),
                ('commitment_section_kicker', models.CharField(default='Cam ket dich vu', max_length=120, verbose_name='Nhan khoi cam ket')),
                ('commitment_section_title', models.CharField(default='Nhung gia tri chinh cua he thong', max_length=180, verbose_name='Tieu de khoi cam ket')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Noi dung trang chu',
                'verbose_name_plural': 'Quan ly trang chu',
            },
        ),
        migrations.CreateModel(
            name='AboutPageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/slides/', verbose_name='Anh slide')),
                ('legacy_static_path', models.CharField(blank=True, default='', max_length=255, verbose_name='Anh tinh du phong')),
                ('alt_text', models.CharField(blank=True, default='', max_length=180, verbose_name='Mo ta anh')),
                ('link_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Lien ket khi bam slide')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thu tu hien thi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang hien thi')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='myapp.aboutpagecontent', verbose_name='Noi dung trang Gioi thieu')),
            ],
            options={
                'verbose_name': 'Slide trang Gioi thieu',
                'verbose_name_plural': 'Slider trang Gioi thieu',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/slides/', verbose_name='Anh slide')),
                ('legacy_static_path', models.CharField(blank=True, default='', max_length=255, verbose_name='Anh tinh du phong')),
                ('alt_text', models.CharField(blank=True, default='', max_length=180, verbose_name='Mo ta anh')),
                ('link_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Lien ket khi bam slide')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thu tu hien thi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang hien thi')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='myapp.homepagecontent', verbose_name='Noi dung trang chu')),
            ],
            options={
                'verbose_name': 'Slide trang chu',
                'verbose_name_plural': 'Slider trang chu',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeCategorySpotlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Tieu de the')),
                ('subtitle', models.CharField(blank=True, default='', max_length=120, verbose_name='Dong phu')),
                ('icon_class', models.CharField(default='fas fa-capsules', max_length=120, verbose_name='Class icon')),
                ('link_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Lien ket the')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thu tu hien thi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang hien thi')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_spotlights', to='myapp.homepagecontent', verbose_name='Noi dung trang chu')),
            ],
            options={
                'verbose_name': 'Muc danh muc noi bat',
                'verbose_name_plural': 'Muc danh muc noi bat',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeServiceCommitmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Tieu de the')),
                ('body', models.TextField(blank=True, default='', verbose_name='Noi dung')),
                ('icon_class', models.CharField(default='fas fa-certificate', max_length=120, verbose_name='Class icon')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thu tu hien thi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang hien thi')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_commitments', to='myapp.homepagecontent', verbose_name='Noi dung trang chu')),
            ],
            options={
                'verbose_name': 'Gia tri cam ket trang chu',
                'verbose_name_plural': 'Gia tri cam ket trang chu',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tieu de')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Duong dan')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Tom tat')),
                ('content', models.TextField(blank=True, default='', verbose_name='Noi dung chi tiet')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Anh dai dien')),
                ('is_published', models.BooleanField(default=True, verbose_name='Da xuat ban')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Thoi diem xuat ban')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thoi diem tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thoi diem cap nhat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles_created', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi tao')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles_updated', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi cap nhat')),
            ],
            options={
                'verbose_name': 'Tin tuc',
                'verbose_name_plural': 'Tin tuc',
                'ordering': ['-published_at', '-created_at', '-id'],
            },
        ),
    ]
