# Generated by Django 6.0.1 on 2026-04-20 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_homepagecontent_aboutpageslide_homeheroslide_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpageslide',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Slide trang Giới thiệu', 'verbose_name_plural': 'Slider trang Giới thiệu'},
        ),
        migrations.AlterModelOptions(
            name='homecategoryspotlightitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Mục danh mục nổi bật', 'verbose_name_plural': 'Mục danh mục nổi bật'},
        ),
        migrations.AlterModelOptions(
            name='homeheroslide',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Slide trang chủ', 'verbose_name_plural': 'Slider trang chủ'},
        ),
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={'verbose_name': 'Nội dung trang chủ', 'verbose_name_plural': 'Quản lý trang chủ'},
        ),
        migrations.AlterModelOptions(
            name='homeservicecommitmentitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Giá trị cam kết trang chủ', 'verbose_name_plural': 'Giá trị cam kết trang chủ'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at', '-created_at', '-id'], 'verbose_name': 'Tin tức', 'verbose_name_plural': 'Tin tức'},
        ),
        migrations.AlterField(
            model_name='aboutpageslide',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Mô tả ảnh'),
        ),
        migrations.AlterField(
            model_name='aboutpageslide',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='myapp.aboutpagecontent', verbose_name='Nội dung trang Giới thiệu'),
        ),
        migrations.AlterField(
            model_name='aboutpageslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/slides/', verbose_name='Ảnh slide'),
        ),
        migrations.AlterField(
            model_name='aboutpageslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hiển thị'),
        ),
        migrations.AlterField(
            model_name='aboutpageslide',
            name='legacy_static_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ảnh tĩnh dự phòng'),
        ),
        migrations.AlterField(
            model_name='aboutpageslide',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Liên kết khi bấm slide'),
        ),
        migrations.AlterField(
            model_name='aboutpageslide',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='homecategoryspotlightitem',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_spotlights', to='myapp.homepagecontent', verbose_name='Nội dung trang chủ'),
        ),
        migrations.AlterField(
            model_name='homecategoryspotlightitem',
            name='icon_class',
            field=models.CharField(default='fas fa-capsules', max_length=120, verbose_name='Lớp CSS biểu tượng'),
        ),
        migrations.AlterField(
            model_name='homecategoryspotlightitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hiển thị'),
        ),
        migrations.AlterField(
            model_name='homecategoryspotlightitem',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Liên kết thẻ'),
        ),
        migrations.AlterField(
            model_name='homecategoryspotlightitem',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='homecategoryspotlightitem',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Dòng phụ'),
        ),
        migrations.AlterField(
            model_name='homecategoryspotlightitem',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Tiêu đề thẻ'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Mô tả ảnh'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='myapp.homepagecontent', verbose_name='Nội dung trang chủ'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/slides/', verbose_name='Ảnh slide'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hiển thị'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='legacy_static_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ảnh tĩnh dự phòng'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Liên kết khi bấm slide'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='category_section_kicker',
            field=models.CharField(default='Danh mục nổi bật', max_length=120, verbose_name='Nhãn khối danh mục'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='category_section_link_label',
            field=models.CharField(default='Xem tất cả', max_length=80, verbose_name='Nhãn nút xem thêm danh mục'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='category_section_link_url',
            field=models.CharField(blank=True, default='/products/', max_length=255, verbose_name='Liên kết nút danh mục'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='category_section_title',
            field=models.CharField(default='Tìm thuốc theo nhóm sản phẩm', max_length=180, verbose_name='Tiêu đề khối danh mục'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='commitment_section_kicker',
            field=models.CharField(default='Cam kết dịch vụ', max_length=120, verbose_name='Nhãn khối cam kết'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='commitment_section_title',
            field=models.CharField(default='Những giá trị chính của hệ thống', max_length=180, verbose_name='Tiêu đề khối cam kết'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_autoplay_interval',
            field=models.PositiveIntegerField(default=4000, verbose_name='Thời gian chuyển slide (ms)'),
        ),
        migrations.AlterField(
            model_name='homeservicecommitmentitem',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='homeservicecommitmentitem',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_commitments', to='myapp.homepagecontent', verbose_name='Nội dung trang chủ'),
        ),
        migrations.AlterField(
            model_name='homeservicecommitmentitem',
            name='icon_class',
            field=models.CharField(default='fas fa-certificate', max_length=120, verbose_name='Lớp CSS biểu tượng'),
        ),
        migrations.AlterField(
            model_name='homeservicecommitmentitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hiển thị'),
        ),
        migrations.AlterField(
            model_name='homeservicecommitmentitem',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='homeservicecommitmentitem',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Tiêu đề thẻ'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Nội dung chi tiết'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Đã xuất bản'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xuất bản'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
    ]
