# Generated by Django 6.0.1 on 2026-04-21 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_aboutpageslide_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeaturedBranchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Tên chi nhánh')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Mô tả ngắn')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ hiển thị')),
                ('hours', models.CharField(blank=True, default='', max_length=120, verbose_name='Giờ hoạt động')),
                ('badge', models.CharField(blank=True, default='', max_length=120, verbose_name='Nhãn nổi trên ảnh')),
                ('map_note', models.CharField(blank=True, default='', max_length=180, verbose_name='Ghi chú phụ')),
                ('icon_class', models.CharField(default='fas fa-clinic-medical', max_length=120, verbose_name='Lớp CSS biểu tượng')),
                ('link_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Liên kết khi bấm')),
                ('link_label', models.CharField(blank=True, default='Xem chi nhánh', max_length=80, verbose_name='Nhãn nút liên kết')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/branches/', verbose_name='Ảnh chi nhánh')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_branch_items', to='myapp.aboutpagecontent', verbose_name='Nội dung trang Giới thiệu')),
            ],
            options={
                'verbose_name': 'Chi nhánh tiêu biểu trang Giới thiệu',
                'verbose_name_plural': 'Chi nhánh tiêu biểu trang Giới thiệu',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
