# Generated by Django 6.0.1 on 2026-04-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_aboutfeaturedbranchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutfeaturedbranchitem',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_featured_entries', to='myapp.pharmacy', verbose_name='Chi nhánh lấy từ hệ thống'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='show_branch_role_section',
            field=models.BooleanField(default=True, verbose_name='Hiển thị khối vai trò chi nhánh'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='show_branch_showcase_section',
            field=models.BooleanField(default=True, verbose_name='Hiển thị khối chi nhánh tiêu biểu'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='show_cta_section',
            field=models.BooleanField(default=True, verbose_name='Hiển thị khối lời kêu gọi hành động'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='show_journey_section',
            field=models.BooleanField(default=True, verbose_name='Hiển thị khối hành trình vận hành'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='show_stats_section',
            field=models.BooleanField(default=True, verbose_name='Hiển thị khối thống kê'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='show_story_section',
            field=models.BooleanField(default=True, verbose_name='Hiển thị khối câu chuyện'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='show_value_section',
            field=models.BooleanField(default=True, verbose_name='Hiển thị khối giá trị nổi bật'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=280, verbose_name='Mo ta ngan hien thi ngoai danh sach'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mo ta chi tiet'),
        ),
        migrations.CreateModel(
            name='AboutCustomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(blank=True, default='', max_length=120, verbose_name='Nhãn khối')),
                ('title', models.CharField(max_length=180, verbose_name='Tiêu đề khối')),
                ('body', models.TextField(blank=True, default='', verbose_name='Nội dung khối')),
                ('icon_class', models.CharField(default='fas fa-layer-group', max_length=120, verbose_name='Lớp CSS biểu tượng')),
                ('link_label', models.CharField(blank=True, default='', max_length=80, verbose_name='Nhãn nút liên kết')),
                ('link_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Liên kết nút')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_blocks', to='myapp.aboutpagecontent', verbose_name='Nội dung trang Giới thiệu')),
            ],
            options={
                'verbose_name': 'Khối tùy chỉnh trang Giới thiệu',
                'verbose_name_plural': 'Khối tùy chỉnh trang Giới thiệu',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
