# Generated by Django 6.0.1 on 2026-04-21 11:51

import django.db.models.deletion
from django.db import migrations, models


def seed_about_builtin_sections(apps, schema_editor):
    AboutPageContent = apps.get_model('myapp', 'AboutPageContent')
    AboutBuiltinSection = apps.get_model('myapp', 'AboutBuiltinSection')

    section_flags = [
        ('stats', 'show_stats_section', 10),
        ('story', 'show_story_section', 20),
        ('value', 'show_value_section', 30),
        ('journey', 'show_journey_section', 40),
        ('branch_role', 'show_branch_role_section', 50),
        ('branch_showcase', 'show_branch_showcase_section', 60),
        ('cta', 'show_cta_section', 70),
    ]

    rows_to_create = []
    for content in AboutPageContent.objects.all():
        for section_key, flag_name, sort_order in section_flags:
            if getattr(content, flag_name, True):
                rows_to_create.append(
                    AboutBuiltinSection(
                        content_id=content.pk,
                        section_key=section_key,
                        sort_order=sort_order,
                    )
                )

    if rows_to_create:
        AboutBuiltinSection.objects.bulk_create(rows_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_aboutfeaturedbranchitem_pharmacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBuiltinSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('stats', 'Khối thống kê nhanh'), ('story', 'Khối câu chuyện hệ thống'), ('value', 'Khối giá trị nổi bật'), ('journey', 'Khối hành trình vận hành'), ('branch_role', 'Khối vai trò chi nhánh'), ('branch_showcase', 'Khối chi nhánh tiêu biểu'), ('cta', 'Khối lời kêu gọi hành động')], max_length=40, verbose_name='Loại khối hệ thống')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builtin_sections', to='myapp.aboutpagecontent', verbose_name='Nội dung trang Giới thiệu')),
            ],
            options={
                'verbose_name': 'Khối hệ thống trang Giới thiệu',
                'verbose_name_plural': 'Khối hệ thống trang Giới thiệu',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('content', 'section_key'), name='uniq_about_builtin_section_per_page')],
            },
        ),
        migrations.RunPython(seed_about_builtin_sections, migrations.RunPython.noop),
    ]
