# Generated by Django 6.0.1 on 2026-04-30 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_aboutbuiltinsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thoi gian xac nhan thanh toan'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Nhan vien xac nhan thanh toan'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chu thanh toan'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/', verbose_name='Anh chung tu thanh toan'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_admin_note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chu duyet don thuoc'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chu don thuoc cua khach'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/proofs/', verbose_name='Anh don thuoc'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thoi gian duyet don thuoc'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_reviewed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Nhan vien duyet don thuoc'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_status',
            field=models.CharField(choices=[('not_required', 'Không yêu cầu đơn thuốc'), ('pending', 'Chờ duyệt đơn thuốc'), ('approved', 'Đơn thuốc hợp lệ'), ('rejected', 'Từ chối đơn thuốc')], default='not_required', max_length=20, verbose_name='Trang thai don thuoc'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('packing', 'Đang chuẩn bị'), ('shipping', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('failed_delivery', 'Giao không thành công')], default='pending', max_length=20, verbose_name='Trang thai don'),
        ),
    ]
