# Generated by Django 6.0.1 on 2026-05-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_order_payment_prescription_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPrescriptionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescriptions/proofs/', verbose_name='Anh don thuoc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_proof_images', to='myapp.order')),
            ],
            options={
                'verbose_name': 'Anh don thuoc cua don hang',
                'verbose_name_plural': 'Anh don thuoc cua don hang',
                'ordering': ['id'],
            },
        ),
    ]
