# Generated by Django 6.0.1 on 2026-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_order_prescription_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountotpchallenge',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Đặt lại mật khẩu'), ('username_recovery', 'Khôi phục tên đăng nhập'), ('registration', 'Kích hoạt tài khoản đăng ký')], db_index=True, max_length=40, verbose_name='Mục đích xác thực'),
        ),
    ]
