from django.urls import path

from . import views

urlpatterns = [
    path('db-media/<path:file_name>', views.serve_db_media_file, name='db_media_file'),
    path('', views.home, name='home'),
    path('about/', views.about_view, name='about'),
    path('news/', views.news_list_view, name='news_list'),
    path('news/<slug:slug>/', views.news_detail_view, name='news_detail'),
    path('products/', views.product_list, name='product_list'),
    path('products/<int:medicine_id>/', views.medicine_detail, name='medicine_detail'),
    path('products/<int:medicine_id>/review/', views.submit_medicine_review, name='submit_medicine_review'),
    path('api/products/<int:medicine_id>/reviews/', views.medicine_reviews_api, name='medicine_reviews_api'),
    path('map/', views.map_view, name='map_view'),

    path('cart/', views.cart_detail, name='cart_detail'),
    path('add-to-cart/<int:medicine_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/item/<int:item_id>/update/', views.update_cart_item, name='update_cart_item'),
    path('remove-item/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),

    path('checkout/', views.checkout, name='checkout'),
    path('order/', views.checkout, name='order_create'),

    path('register/', views.register_view, name='register'),
    path('register/activate/<uidb64>/<token>/', views.activate_account_view, name='activate_account'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password-reset/', views.account_recovery_request_view, name='password_reset'),
    path('password-reset/verify/<uuid:token>/', views.account_recovery_verify_view, name='account_recovery_verify'),
    path('password-reset/done/', views.account_recovery_password_complete_view, name='password_reset_done'),
    path('username-recovery/done/', views.username_recovery_complete_view, name='username_recovery_complete'),
    path('reset/<uidb64>/<token>/', views.legacy_password_reset_redirect_view, name='password_reset_confirm'),
    path('reset/done/', views.account_recovery_password_complete_view, name='password_reset_complete'),
    path('account/', views.account_view, name='account'),
    path('history/', views.order_history, name='order_history'),
    path('history/<int:order_id>/', views.order_history_detail, name='order_history_detail'),
    path('history/<int:order_id>/items/<int:item_id>/review/', views.order_item_review_redirect, name='order_item_review_redirect'),
    path('history/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
    path('history/<int:order_id>/confirm-received/', views.confirm_order_received, name='confirm_order_received'),
    path('history/<int:order_id>/return-request/', views.create_or_update_return_request, name='return_request'),
    path('history/invoice/<int:order_id>/', views.order_invoice_view, name='order_invoice_view'),

    path('pharmacy/<int:pharmacy_id>/', views.pharmacy_detail, name='pharmacy_detail'),
    path('pharmacy/<int:pharmacy_id>/review/', views.submit_pharmacy_review, name='submit_pharmacy_review'),
    path('api/pharmacies/<int:pharmacy_id>/reviews/', views.pharmacy_reviews_api, name='pharmacy_reviews_api'),

    path('api/route/', views.get_route_api, name='api_route'),
    path('api/find-best-pharmacy/', views.find_best_pharmacy_api_v2, name='find_best_pharmacy_api'),
    path('api/nearest-pharmacy/', views.find_best_pharmacy_api_v2, name='nearest_pharmacy_api'),
    path('api/catalog-search/', views.catalog_search_api, name='catalog_search_api'),
    path('api/pharmacies-nearby/', views.nearby_pharmacies_api, name='nearby_pharmacies_api'),
    path('api/search-address/', views.search_address_api, name='search_address_api'),
    path('api/reverse-address/', views.reverse_address_api, name='reverse_address_api'),
    path('api/save-profile-address/', views.save_profile_address_api, name='save_profile_address_api'),
    path('api/payment-preview/', views.payment_preview_api, name='payment_preview_api'),
    path('api/editor-upload/', views.editor_upload_api, name='editor_upload_api'),
    path('error-preview/<int:status_code>/', views.error_preview, name='error_preview'),

    path('admin/', views.custom_admin_dashboard, name='custom_admin_dashboard'),
    path('admin/home-page/', views.custom_admin_home_page, name='custom_admin_home_page'),
    path('admin/about-page/', views.custom_admin_about_page, name='custom_admin_about_page'),
    path('admin/reports/', views.custom_admin_reports, name='custom_admin_reports'),
    path('admin/reports/export.xlsx', views.custom_admin_reports_export_excel, name='custom_admin_reports_export_excel'),
    path('admin/review-insights/', views.custom_admin_review_insights, name='custom_admin_review_insights'),
    path('admin/permissions/', views.custom_admin_permissions_center, name='custom_admin_permissions_center'),
    path('admin/order/<int:pk>/', views.custom_admin_order_detail, name='custom_admin_order_detail'),
    path('admin/return-request/<int:pk>/', views.custom_admin_return_request_detail, name='custom_admin_return_request_detail'),
    path('admin/purchase-import/<int:pk>/', views.custom_admin_purchase_import_detail, name='custom_admin_purchase_import_detail'),
    path('admin/purchase-import/<int:pk>/receipt/', views.custom_admin_purchase_import_receipt, name='custom_admin_purchase_import_receipt'),
    path('admin/stock-export/<int:pk>/', views.custom_admin_stock_export_detail, name='custom_admin_stock_export_detail'),
    path('admin/stock-export/<int:pk>/receipt/', views.custom_admin_stock_export_receipt, name='custom_admin_stock_export_receipt'),
    path('admin/stock-export/<int:pk>/excel/', views.custom_admin_stock_export_excel, name='custom_admin_stock_export_excel'),
    path('admin/<str:model_key>/', views.custom_admin_list, name='custom_admin_list'),
    path('admin/<str:model_key>/create/', views.custom_admin_create, name='custom_admin_create'),
    path('admin/<str:model_key>/<int:pk>/edit/', views.custom_admin_update, name='custom_admin_update'),
    path('admin/<str:model_key>/<int:pk>/delete/', views.custom_admin_delete, name='custom_admin_delete'),
]
